### PR TITLE
now using typescript and @types

### PR DESCRIPTION
**Pull request by lholznagel**
## Description

Implemented inversify/InversifyJS#306
## Related Issue

inversify/InversifyJS#306
## Motivation and Context

inversify/InversifyJS#306
## How Has This Been Tested?

CI
Local
Sometimes the MongoDB makes problems :(
## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [X] Breaking change (fix or feature that would cause existing functionality to change)
## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] My change requires a change to the type definitions.
- [X] I have updated the type definitions accordingly.
- [X] I have read the **CONTRIBUTING** document.
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Comment by lholznagel** [comment]
```
Uncaught Error: Request logging is disabled
      at Object.exports.assert (node_modules/hoek/lib/index.js:736:11)
      at internals.Request.getLog (node_modules/hapi/lib/request.js:252:10)
      at new exports.GreatResponse (node_modules/good/lib/utils.js:142:24)
      at Object.exports.GreatResponse (node_modules/good/lib/utils.js:83:16)
      at internals.Monitor._responseHandler (node_modules/good/lib/monitor.js:244:33)
      at invoke (node_modules/podium/lib/index.js:239:30)
      at each (node_modules/podium/lib/index.js:243:13)
      at Object.exports.parallel (node_modules/podium/node_modules/items/lib/index.js:70:13)
      at Object.internals.emit (node_modules/podium/lib/index.js:260:18)
      at internals.Podium._emit (node_modules/podium/lib/index.js:140:15)
      at each (node_modules/podium/lib/index.js:181:47)
      at Object.exports.parallel (node_modules/podium/node_modules/items/lib/index.js:70:13)
      at relay (node_modules/podium/lib/index.js:182:15)
      at Object.internals.emit (node_modules/podium/lib/index.js:186:16)
      at Immediate.setImmediate (node_modules/podium/lib/index.js:169:38)
```

When rerunning the test it should work (locally its like this). Seems like there is a race condition in preparing the database. Looking into it

**Comment by remojansen** [comment]
Hi @lholznagel thanks for this I will review and enable TravisCI later on...

**Comment by remojansen** [comment]
Hi @Talento90 do you know what could be the problem? Thanks for your help!

**Comment by lholznagel** [comment]
I think this can be closed?

**Comment by remojansen** [comment]
Yes, I don't know what to do about this example. Maybe we should create one from scratch?

**Comment by lholznagel** [comment]
I don´t know the status of all examples, maybe an overall cleanup/extension?

**Comment by remojansen** [comment]
The only "dead" repo is the hapi example. The devtools are not ready but I will get back to then at some point. All the other libraries and examples are working fine but I need to upgrade the dependencies by hand because some of them include breaking changes.

**Comment by lholznagel** [comment]
Okay, maybe I revisit this pr in the next days and see if I can resolve the problem

**Comment by remojansen** [comment]
Thanks a lot :+1:

**Pull request closed without merging**
